[normalizeParagraph] Normalizando parágrafos.
VitorLuizC/normalize-text pull request #1
Opened 2018-01-27 14:13 UTC by zscaiosi

Algumas vezes eu recebo textos de clientes e/ou documentos que deveriam ser parágrafos, porém estão sem pontuação e sem começar com maiúscula.

normalizeParagraph() faz isso.

2018-01-28 22:56 UTC, VitorLuizC requested changes
Assim que os pontos forem corrigidos eu faço o Merge sem problema algum.

2018-01-28 22:56 UTC, VitorLuizC commented on src/index.js
> +  (value) => normalize(value, 'NFKD')
Porque você normaliza no `NFKD`? Acho mais útil começar a composição com o `normalizeWhitespaces` e não mexer nos diacríticos.

2018-01-28 22:56 UTC, VitorLuizC commented on src/index.js
> +  (value) => value.indexOf(".") === value.length-1 ? value : value+".",
Alguns pontos nessa linha.

1. Desacopla o `indexOf` como os outros métodos na linha 5.
    https://github.com/zscaiosi/normalize-text/blob/master/src/index.js#L5

2. Essa comparação tá incorreta. Imagino que um parágrafo possa ter mais de um ponto, `indexOf` retorna o primeiro resultado pra comparação, acho que você deveria checar se o último caractere é um ponto e não se o primeiro ponto encontrado no `indexOf` é o ultimo caractere.
    ```js
    (value) => value[value.length - 1] === '.' ? value : value + '.'
    ```

3. Mantém o padrão de aspas simples, plox.

2018-01-28 22:56 UTC, VitorLuizC commented on src/index.js
> +  (value) => value.replace(value.charAt(0), value.charAt(0).toUpperCase()),
O método `replace` foi desacoplado e está sendo usado nos outros métodos, o uppercase ainda não foi desacoplado. Mas é só fazer como na linha 5.
https://github.com/zscaiosi/normalize-text/blob/master/src/index.js#L5

Outro detalhe é que como a `String` é um iterável você consegue acessar os caracteres como um `Array`.
```js
(value) => replace(value, value[0], uppercase(value[0]))
```

2018-01-30 19:29 UTC, zscaiosi commented on src/index.js
> +  (value) => value.replace(value.charAt(0), value.charAt(0).toUpperCase()),
Cara, eu li sua lib "uncouple" mas não entendi a real diferença que ela faz.
Mas desacoplei!

2018-01-30 19:30 UTC, zscaiosi commented
@VitorLuizC fiz commit --amend e dei push -f, então acho que precisa deletar no seu repo local e fazer git checkou caio-development novamente.

Flww

2018-01-31 10:55 UTC, VitorLuizC commented
@zscaiosi
Vou fazer o merge e publicar \O/

2018-01-31 10:55 UTC, VitorLuizC approved these changes

2018-01-31 10:57 UTC, merged

2018-01-31 11:07 UTC, zscaiosi commented
Ueba!

2018-01-31 11:25 UTC, VitorLuizC commented
Publicado na versão 0.2.0!