#15 Provide tagged string template functions
VitorLuizC/normalize-text pull request #21
Opened 2023-12-29 23:12 UTC by phuvinhbmt

2024-01-02 00:51 UTC, VitorLuizC requested changes

2024-01-02 00:51 UTC, VitorLuizC commented on src/normalizeWhiteSpaces.spec.ts
> +      normalizeWhiteSpaces(` Hi,  ${student.name}!\n How are you doing? `)
@phuvinhbmt I also used the wrong term in the issue, its [tagged templates](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates), and they're little bit different than just supporting string templates. Tagged templates are functions that receives a list os strings as first argument, and the interpolations as the rest of arguments.

```ts
function normalizeWhiteSpaces(parts: TemplateStringArray, ...values: unknown[]): string;
```

```suggestion
  it('supports usage as tagged template', () => {
    const student = { name: 'John   Doe' };
    expect(
      normalizeWhiteSpaces` Hi,  ${student.name}!\n How are you doing? `
```

2024-01-03 12:55 UTC, phuvinhbmt commented
@VitorLuizC I updated `normalizeWhiteSpaces` per your comment. Let me know if it needs updating anything. Thanks

2024-02-13 13:06 UTC, phuvinhbmt commented
@VitorLuizC do you mind having a look at this pr when you have time please ? Cheers

2024-02-13 21:56 UTC, VitorLuizC approved these changes
LGTM

2024-02-13 21:58 UTC, merged

2024-02-13 22:11 UTC, VitorLuizC commented
@phuvinhbmt sorry to take so long, I really have to improve my priorization skills in order to be a good maintainer again. Anyway, your PR was merged, and it was published under version [2.5.0](https://github.com/VitorLuizC/normalize-text/releases/tag/2.5.0).

Thank you a lot!